package opencode_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestNoGeneratedHeaderInCustomFiles ensures that non-generated Go files
// do not contain the "Code generated by oapi-codegen DO NOT EDIT." header.
// This is a belt-and-suspenders guardrail alongside the CI git diff check
// that asserts regen only touches *.gen.go files.
func TestNoGeneratedHeaderInCustomFiles(t *testing.T) {
	const marker = "Code generated by oapi-codegen DO NOT EDIT"

	err := filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		// Only check .go files.
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		// Skip test files — they are always hand-written.
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}
		// Generated files are expected to have the marker.
		if strings.HasSuffix(path, ".gen.go") {
			return nil
		}
		// Skip vendor.
		if strings.HasPrefix(path, "vendor/") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.Contains(string(data), marker) {
			t.Errorf("custom file %q contains generated marker %q — it should not be hand-edited or should be renamed to *.gen.go", path, marker)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk: %v", err)
	}
}

// TestGeneratedFilesHaveMarker ensures that generated files DO contain the
// "DO NOT EDIT" marker so they are easily identifiable.
func TestGeneratedFilesHaveMarker(t *testing.T) {
	const marker = "Code generated by"

	files, err := filepath.Glob("*.gen.go")
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	if len(files) == 0 {
		t.Fatal("no *.gen.go files found")
	}
	for _, f := range files {
		data, err := os.ReadFile(f)
		if err != nil {
			t.Errorf("read %s: %v", f, err)
			continue
		}
		if !strings.Contains(string(data), marker) {
			t.Errorf("generated file %q is missing the %q marker", f, marker)
		}
	}
}
